### ISSUE TITLE
How to import pipeline into StreamSets Data Collector container

### ISSUE THREAD

**Issue by loktiing** [mapr-demos/predictive-maintenance#3]
Hi, 

I am new to StreamSets. Currently I have run the following data collector container:
docker run -it -p 18630:18630 -d --name sdc --network mynetwork streamsets/datacollector

My question is how to import the following JSON pipeline file:
wget https://raw.githubusercontent.com/mapr-demos/predictive-maintenance/master/StreamSets/MQTT%20File%20Tail.json

into the SCD?

I am trying to google around, but could not find a simpler way to do it. Mostly requires us to register StreamSets account, which I think is not necessary in this case. Please help! Thanks!

**Comment by tdunning** [comment]
This is really a StreamSets question.

You can download this file by cloning the git repository. From there, you should use StreamSets capabilities to upload the json file to StreamSets. There is likely some sort of "upload file" capability, but you would have to work with them to figure that out.

Good luck!
